import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'estacion.settings')
django.setup()

from estaciones.models import Estacion

estaciones = [
    Estacion(razon_social='G Y F LTDA', url='10.101.41.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MELTA LTDA', url='10.2.113.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='RAISAN LTDA', url='10.2.126.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Sedaler SA', url='10.2.224.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Marturet S. y Arrieta M', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Mountline S.A. - Ancap Las Toscas', url='10.2.5.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Bregu SRL', url='10.2.24.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Goobas S.A', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Roble Fuerte S.A', url='10.22.87.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='REMITEC S.A.', url='10.101.49.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='AGENCIA PINAMAR S.R.L.', url='192.168.0.200', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ARCO LTDA.', url='10.2.14.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='SANTA LUCIA LUCIA LTDA', url='10.81.123.210', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='SERVICENTRO SAYAGO', url='10.2.100.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='FANIRAL S.A.', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Marbi Ltda', url='10.2.245.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Rostan Ltda', url='10.2.210.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ELGORRIAGA SRL', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ESSO SOLYMAR S.R.L.', url='10.22.23.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Artliss S.A.', url='192.168.1.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Legamar', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='PASEL S.A', url='192.168.0.25', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='BYD S.R.L.', url='10.2.32.11', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='LA PLAZA LTDA', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Lardey S.A.', url='10.22.27.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Vientonor S.A.', url='192.168.40.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Larrañaga S.A', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estación San Luis Ltda', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='DINEX S.R.L', url='10.2.9.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ZAGREB LTDA.', url='10.2.227.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Acronar S.A', url='10.22.22.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Gottero Hnos Ltda', url='192.168.2.25', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Servicentro Florida S.R.L.', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Lancam srl', url='10.2.116.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='BAT Ltda', url='10.22.57.2', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='BDB LTDA', url='10.2.247.15', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='LUIS OTTONELLO Y CIA S.A.', url='10.2.106.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estación del Norte SRL', url='10.22.84.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Js Ltda', url='10.22.77.2', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Premilar S.A', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ESTACION LA TEJA', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Takel Ltda', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='PINARES DE ATLANTIDA SRL', url='10.2.6.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Arocena SRL', url='10.2.117.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Orofil S.A.', url='10.101.150.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='FESTYLEND S.A.', url='10.22.83.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='NICRE LTDA.', url='10.2.123.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='PARAJE DIAMANTE - San Carlos', url='10.2.87.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='PARAJE DIAMANTE - Ruta 39', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Francisco Beisso Quijano - 18 de Julio', url='192.168.2.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Francisco Beisso Quijano - Punta de Santiago', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='RUTA DOCE S.A.', url='10.22.95.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estacion Capurro SRL', url='10.2.244.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Dresur S.A.', url='10.2.58.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='N Y R', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ULBINDAR S.A.', url='10.81.121.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ROCCA Y CIA SA Centro', url='10.2.158.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ROCCA Y CIA SA Centro (POS 3G)', url='190.64.213.147', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Ilanir S.A', url='10.2.190.100', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='LAGOMAR LTDA.', url='10.2.8.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='Debe configurarse IP estatica en el POS'),
    Estacion(razon_social='Gasolinera Cortinas Ltda', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='CYNEL S.A - Ruta', url='10.2.218.10', direccion='iJServ_Web', puerto='8180', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='CYNEL S.A - Centro', url='10.2.219.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='XITALIA S.A', url='192.168.2.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='BELLA ITALIA SENC', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='POSPISTA', clave='POSPISTA', observacion='nan'),
    Estacion(razon_social='MALCAR S.R.L.', url='10.2.129.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='NAPAZ SAN JOSE S.R.L', url='10.2.131.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='SUCESORES DE LUIS ALBERTO ROCCA', url='192.168.66.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Parada 19', url='192.168.0.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='TAFIBEL S.A', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='DUCIANA S.A.', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='TIENE POS 3G COMBUSTIBLE (estacion.digilarmcctv.com)'),
    Estacion(razon_social='SERVICIOS CARMELO S.R.L.', url='179.27.214.182', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='TIENE POS 3G COMBUSTIBLE'),
    Estacion(razon_social='ESTACION ANCAP TACHI', url='192.168.2.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='LIBERTADOR S.R.L.', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARFALUB S.A.', url='10.2.229.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ESSO SOLYMAR S.R.L.', url='10.22.23.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Pontinvrea', url='10.2.250.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='PEDRO MAS COCARO Y CIA SRL', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='G Y F Suc. Vergara', url='10.102.172.4', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='FANIRAL S.A.', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Libertador S.R.L', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ROCCA Y CIA SA Ruta', url='10.2.167.10', direccion='iJServ_Web', puerto='8180', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estacion de Servicio MARNE', url='10.2.115.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Radial Mercedes Ltda Ruta', url='10.2.237.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Radial Mercedes Ltda Centro', url='192.168.10.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='JIGAMA LTDA', url='10.22.67.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='DISTANCIA S.A.', url='10.22.64.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Verdera e Hijo SRL', url='10.2.118.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Carlos A. Otero LTDA', url='10.101.80.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estacion Olimpia', url='10.2.249.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Jilfer S.A.', url='10.2.184.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='CLIWEL SA', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Mileban S.A', url='10.2.214.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='TONYTEC S.A.', url='10.22.88.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ANCAP PARQUE RIVERA - GRAND PRIX LTDA', url='10.22.89.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Ancap Santa Rita', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ALQUIMIA 4 LTDA - Estacion Ancap', url='10.2.102.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ROGUL SRL', url='10.2.155.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Celemyr Aeropuerto', url='10.2.34.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ANCAP RUTA 11', url='10.2.23.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='SERVICENTRO RUTA 3 - Ofissi S.A', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Celemyr CAR ONE', url='10.2.210.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='AXION Rocha - Anferal Ltda', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estacion Trouville - Celemyr S.A', url='10.2.208.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Migliaro Centro', url='10.222.105.30', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Migliaro Termas - Ruta', url='11.222.104.30', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Migliaro Parque - Amorin', url='11.222.106.30', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Bracoral S.A', url='10.1.11.25', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ANCAP LA PALOMA - ESTEKORAL', url='10.2.161.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ROCCA Y CIA SA J P Ramirez', url='192.168.1.25', direccion='iJServ_Web', puerto='8180', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Automovil Club del Uruguay', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Ancap Centro Flores', url='10.2.66.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ANCAP ROOSEVELT - Gabeler', url='172.16.10.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ANCAP Cerro Colorado', url='10.2.70.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='DISA PANDO - Botirel S.A', url='192.168.16.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='SERVICENTRO AXION MODELO', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Juan Cariboni - Ancap Chuy', url='10.2.163.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estacion el Molino', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Estacion AXION Nueva Palmira / Ruta 12 km 2', url='10.22.24.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='STI ROOSEVELT', url='10.2.97.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='STI CALLE 20 Y 30', url='192.168.10.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Ancap Cufre', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Ancap Toledo Chico', url='10.2.106.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='RIMAN', url='119.8.148.54', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='SERVICENTRO CIUDAD DE LA COSTA (Autopro)', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ANCAP SAN GREGORIO DE POLANCO // QUILTIC S.A', url='192.168.1.33', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Axion ESSO DEL NORTE // KIMDAN SA', url='172.16.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='AXION SERVICENTRO PLAZA COLON', url='192.168.3.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Axion Ruta Trinidad - Cosdony S.A', url='192.168.3.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Ancap Costanera - Itinol S.A', url='10.2.133.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Midebal S.A.', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Rigual SRL', url='192.168.1.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ANCAP Mec Ltda', url='10.2.31.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='FERBRA SRL // ANCAP SANTA ROSA', url='10.2.17.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Sintel', url='10.2.77.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='AXION BELVEDERE', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A TREINTA Y TRES', url='192.168.1.211', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A MELO', url='192.168.2.210', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A RIO BRANCO', url='10.2.254.210', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A BELLA UNION', url='192.168.50.205', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A TOMAS GOMENZORO', url='192.168.60.210', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A CHARQUEADA', url='192.168.20.210', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A CEBOLLATI', url='192.168.30.210', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='MARIMAR S.A VELAZQUEZ', url='192.168.40.210', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Arrieta y Sanguinet Soc. de Hecho - Servicentro El Tigre', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Foical S.A', url='10.22.28.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Delmar SRL', url='192.168.1.20', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Distancia S.A - Estacion America', url='10.22.64.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='KALTIN S.A. - AXION COLONIA', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='SERVICENTRO ESSO - Angeral', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='CASA ELIO OCAMPOS RODRIGUEZ - OCAMPOS S.C.', url='10.2.175.200', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='CASA ELIO OCAMPOS Parque/Ruta - OCAMOS S.C', url='10.2.174.200', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='CASA ELIO OCAMPOS CENTRO - OCAMOS S.C', url='10.2.173.200', direccion='iJServ_Web', puerto='8180', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='ESTACION SILVEIRA HNOS S.R.L.', url='192.168.1.90', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Ancap Atlantida - Pinares del Atlantida', url='10.2.6.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Proburgues SRL', url='10.22.75.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Disa Rocha - Autoservicios Ltda', url='192.168.66.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Lazcano SA - Axion Lazcano', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Axion Vorgan SA', url='192.168.0.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Servitexxa', url='10.2.251.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Axion IWILL', url='192.168.168.250', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='VICTORIA I S.R.L.', url='10.2.198.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='PONILOR SAS - AXION ENERGY - NEXZUR', url='192.168.5.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
    Estacion(razon_social='Axion San Blas', url='192.168.1.10', direccion='iJServ_Web', puerto='8080', usuario='pospista', clave='pospista', observacion='nan'),
]

Estacion.objects.bulk_create(estaciones)
print("Estaciones insertadas con éxito.")
