# Generated by Django 5.1 on 2024-09-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('puerto', models.IntegerField()),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
